import Head from "next/head"

export default function Meta () {
  return (
    <Head>
        <title>OPEN TABLE APP NEXT JS</title>
        <meta name="description" content="Generated by open table next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
